'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { calculateBasket, calculateLine, findAddressResults, formatDistance, getPrice, money, products, searchProducts, stores, type Product } from '@/lib/data';

type Basket = Record<string, number>;
const initialBasket: Basket = { milk: 1, cereal: 2, tomatoes: 1 };

export default function Home() {
  const [selectedStore, setSelectedStore] = useState(stores[0].id);
  const [query, setQuery] = useState('');
  const [basket, setBasket] = useState<Basket>(initialBasket);
  const [locationLabel, setLocationLabel] = useState('תל אביב-יפו');
  const [locationQuery, setLocationQuery] = useState('');
  const [locationOpen, setLocationOpen] = useState(false);
  const [locationError, setLocationError] = useState('');
  const [storeOpen, setStoreOpen] = useState(false);
  const [compareOpen, setCompareOpen] = useState(false);
  const [liveMessage, setLiveMessage] = useState('');
  const basketHydrated = useRef(false);

  useEffect(() => { window.requestAnimationFrame(() => { try { const saved = window.localStorage.getItem('sal-zol-basket'); if (saved) setBasket(JSON.parse(saved) as Basket); } catch { /* A corrupt local basket should not prevent shopping. */ } basketHydrated.current = true; }); }, []);
  useEffect(() => { if (basketHydrated.current) window.localStorage.setItem('sal-zol-basket', JSON.stringify(basket)); }, [basket]);
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); document.getElementById('product-search')?.focus(); } }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); }, []);

  const filteredProducts = useMemo(() => searchProducts(query), [query]);
  const selectedStoreData = stores.find((store) => store.id === selectedStore) ?? stores[0];
  const calculation = useMemo(() => calculateBasket(basket, selectedStore), [basket, selectedStore]);
  const itemCount = Object.values(basket).reduce((sum, quantity) => sum + quantity, 0);
  const basketProducts = products.filter((product) => basket[product.id]);
  const alternateStore = stores.find((store) => store.id !== selectedStore) ?? stores[1];
  const alternateCalculation = useMemo(() => calculateBasket(basket, alternateStore.id), [basket, alternateStore.id]);
  const savings = Math.max(0, calculation.publicTotal - alternateCalculation.publicTotal);

  function updateBasket(product: Product, change: number) {
    const current = basket[product.id] ?? 0; const next = Math.max(0, Math.min(99, current + change));
    setBasket((previous) => { const copy = { ...previous }; if (next) copy[product.id] = next; else delete copy[product.id]; return copy; });
    setLiveMessage(next ? `${product.name}, ${next} יחידות בסל` : `${product.name} הוסר מהסל`);
  }
  function chooseStore(storeId: string) { setSelectedStore(storeId); setStoreOpen(false); const store = stores.find((item) => item.id === storeId); if (store) setLiveMessage(`הסניף הנבחר: ${store.name}`); }
  function useBrowserLocation() {
    setLocationError('');
    if (!navigator.geolocation) { setLocationError('הדפדפן לא תומך במיקום. אפשר לחפש כתובת במקום.'); return; }
    navigator.geolocation.getCurrentPosition(() => { setLocationLabel('המיקום שלך'); setLocationOpen(false); setLiveMessage('המיקום זוהה בהצלחה'); }, () => setLocationError('לא הצלחנו לקבל הרשאת מיקום. אפשר לחפש כתובת באופן ידני.'), { timeout: 6000 });
  }
  function chooseAddress(label: string) { setLocationLabel(label); setLocationOpen(false); setLocationQuery(''); setLiveMessage(`נבחרה כתובת: ${label}`); }
  const addressResults = findAddressResults(locationQuery);

  return <main className="app-shell" dir="rtl">
    <a className="skip-link" href="#product-search">דלגו לתוכן הראשי</a>
    <header className="topbar"><div className="brand-lockup" aria-label="סל זול"><span className="brand-mark" aria-hidden="true">ס</span><span><strong>סל זול</strong><small>קונים חכם, משלמים פחות</small></span></div><div className="topbar-actions"><button className="location-pill" onClick={() => setLocationOpen(true)} aria-label={`שינוי מיקום, ${locationLabel}`}><span className="pin" aria-hidden="true">⌖</span><span>{locationLabel}</span><span className="chevron" aria-hidden="true">⌄</span></button><button className="icon-button" aria-label="הודעות" onClick={() => setLiveMessage('אין הודעות חדשות')}>♧</button><button className="avatar" aria-label="הפרופיל שלי">א</button></div></header>
    <div className="page-grid"><section className="main-column" aria-labelledby="page-title"><div className="welcome-row"><div><p className="eyebrow">יום ראשון, 30 באוגוסט</p><h1 id="page-title">הקנייה השבועית,<br /><span>במחיר הכי טוב.</span></h1><p className="intro">מצאנו עבורך את המחירים המשתלמים ביותר בסביבה שלך.</p></div><div className="basket-badge" aria-label={`${itemCount} פריטים בסל`}><span aria-hidden="true">🛒</span><strong>{itemCount}</strong><span>פריטים בסל</span></div></div><div className="search-wrap"><span className="search-icon" aria-hidden="true">⌕</span><input id="product-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="חפש מוצר, מותג או ברקוד..." aria-label="חיפוש מוצר, מותג או ברקוד" /><kbd>⌘ K</kbd></div>
      <div className="section-heading"><div><h2>מה קורה בסביבה</h2><p>מחירים שנבדקו לאחרונה בסניפים הקרובים</p></div><button className="text-button" onClick={() => setStoreOpen((open) => !open)}>{storeOpen ? 'סגירת הסניפים' : 'החלף סניף'} <span aria-hidden="true">←</span></button></div><div className="store-strip" aria-label="בחירת סניף">{stores.map((store) => <button key={store.id} className={`store-card ${selectedStore === store.id ? 'active' : ''}`} onClick={() => chooseStore(store.id)} aria-pressed={selectedStore === store.id}><span className={`store-logo ${store.color}`}>{store.chain.slice(0, 1)}</span><span className="store-copy"><strong>{store.name}</strong><small>{formatDistance(store.distanceKm)} · {store.openNow ? 'פתוח עכשיו' : 'סגור'}</small></span>{selectedStore === store.id && <span className="check" aria-hidden="true">✓</span>}</button>)}</div>{storeOpen && <div className="store-note" role="status">ההשוואה מציגה מחירים לפי סניף. בחרו סניף כדי לעדכן את הסל ואת תוצאות החיפוש.</div>}
      <div className="section-heading products-heading"><div><h2>מומלץ להוסיף לסל</h2><p>{filteredProducts.length} מוצרים · עדכון אחרון לפני 12 דקות</p></div><span className="fresh-dot" title="הנתונים התקבלו ממקורות השקיפות של הרשתות">● נתונים חיים</span></div><div className="product-list" aria-live="polite">{filteredProducts.map((product) => { const price = getPrice(product, selectedStore); const quantity = basket[product.id] ?? 0; const line = calculateLine(product, selectedStore, quantity || 1); const publicPromo = product.promotions.find((promotion) => promotion.kind === 'public'); const clubPromo = product.promotions.find((promotion) => promotion.kind === 'club'); return <article className="product-card" key={product.id}><div className={`product-art art-${product.id}`} aria-hidden="true">{product.icon}</div><div className="product-info"><span className="category-label">{product.category}</span><h3>{product.name}</h3><p>{product.brand} · {product.size}</p><div className="tag-row"><span className="product-tag">{product.tag}</span>{publicPromo && <span className="promo-tag">ציבורי: {publicPromo.label}</span>}{clubPromo && <span className="club-tag">מועדון: {money(clubPromo.clubPrice!)}</span>}</div></div><div className="price-column"><strong>{price.available ? money(price.amount!) : 'לא זמין'}</strong><small>{price.unitPrice}</small><span className="updated">נבדק לפני {price.updatedAt === '2026-08-29T18:20:00+03:00' ? '14 שעות' : '12 דקות'}</span>{line.promotionNote && <span className="promotion-note">{line.promotionNote}</span>}</div><div className="product-action">{quantity ? <div className="quantity" aria-label={`כמות ${product.name}`}><button onClick={() => updateBasket(product, -1)} aria-label={`הסר יחידה של ${product.name}`}>−</button><strong>{quantity}</strong><button onClick={() => updateBasket(product, 1)} aria-label={`הוסף יחידה של ${product.name}`}>+</button></div> : <button className="add-button" onClick={() => updateBasket(product, 1)} disabled={!price.available}>+ הוסף</button>}</div></article>; })}{!filteredProducts.length && <div className="empty-state"><strong>לא מצאנו מוצר כזה</strong><span>נסו לחפש לפי שם, מותג או ברקוד אחר.</span><button className="text-button" onClick={() => setQuery('')}>הצגת כל המוצרים</button></div>}</div></section>
      <aside className="basket-panel" aria-labelledby="basket-title"><div className="panel-top"><div><span className="eyebrow">הבחירות שלך</span><h2 id="basket-title">הסל שלי <span>{itemCount}</span></h2></div><button className="more-button" aria-label="ניקוי הסל" onClick={() => setBasket({})}>•••</button></div><div className="basket-store"><span className="store-logo mint">{selectedStoreData.chain.slice(0, 1)}</span><div><strong>{selectedStoreData.name}</strong><small>{selectedStoreData.address}</small></div><span className="open-now">{selectedStoreData.openNow ? 'פתוח' : 'סגור'}</span></div><div className="basket-items">{basketProducts.length ? basketProducts.map((product) => { const line = calculateLine(product, selectedStore, basket[product.id]); return <div className="basket-item" key={product.id}><span className={`mini-art art-${product.id}`} aria-hidden="true">{product.icon}</span><div><strong>{product.name}</strong><small>{basket[product.id]} × {money(getPrice(product, selectedStore).amount ?? 0)}</small>{line.promotionNote && <em>{line.promotionNote}</em>}</div><b>{line.publicTotal === null ? 'לא זמין' : money(line.publicTotal)}</b></div>; }) : <div className="empty-basket">הסל שלך ריק כרגע.<br />הוסיפו מוצרים מהרשימה.</div>}</div>{calculation.unavailable.length > 0 && <div className="unavailable-note" role="alert">{calculation.unavailable.length} מוצר{calculation.unavailable.length > 1 ? 'ים' : ''} לא זמין בסניף הזה. הסכום לא כולל אותו.</div>}{basketProducts.length > 0 && <div className="compare-callout"><span aria-hidden="true">✦</span><div><strong>{savings > 0 ? `אפשר לחסוך ${money(savings)}` : 'הסניף הנבחר משתלם'}</strong><small>{savings > 0 ? `בסניף ${alternateStore.chain}, שנמצא ${formatDistance(alternateStore.distanceKm)} מכאן` : 'המחיר הנמוך ביותר בין הסניפים שנבדקו'}</small></div><button onClick={() => setCompareOpen(true)} aria-label="השוואת סל בין סניפים">←</button></div>}<div className="total-block"><div><span>סה״כ בסניף הנבחר</span><strong>{money(calculation.publicTotal)}</strong></div><div className="club-total"><span>עם הטבות מועדון</span><strong>−{money(calculation.clubSavings)}</strong></div><div className="total-line"><span>סה״כ לתשלום</span><strong>{money(calculation.publicTotal - calculation.clubSavings)}</strong></div></div><button className="primary-action" onClick={() => setCompareOpen(true)}>השוואת הסל המלא <span aria-hidden="true">←</span></button><p className="disclaimer">מחירי המדף עשויים להשתנות בחנות. המחיר בקופה הוא הקובע.</p></aside></div>
    <footer className="site-footer"><span>© 2026 סל זול · נתוני מחירים ממקורות השקיפות של הרשתות</span><nav><a href="https://prices.shufersal.co.il/" rel="noreferrer">מקור נתונים</a><a href="/privacy">פרטיות</a><a href="/terms">תנאי שימוש</a></nav></footer><div className="sr-only" aria-live="polite">{liveMessage}</div>
    {locationOpen && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setLocationOpen(false); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="location-title"><button className="modal-close" onClick={() => setLocationOpen(false)} aria-label="סגירת חלון">×</button><span className="modal-icon">⌖</span><h2 id="location-title">איפה אתם קונים?</h2><p>נמצא את הסניפים הקרובים אליכם. הכתובת משמשת לחיפוש הנוכחי בלבד.</p><button className="location-detect" onClick={useBrowserLocation}>שימוש במיקום הנוכחי <span>⌖</span></button><div className="modal-divider"><span>או חיפוש כתובת</span></div><input autoFocus value={locationQuery} onChange={(event) => { setLocationQuery(event.target.value); setLocationError(''); }} placeholder="רחוב, עיר..." aria-label="חיפוש כתובת" />{addressResults.map((result) => <button className="address-result" key={result.label} onClick={() => chooseAddress(result.label)}><strong>{result.label}</strong><small>{result.detail}</small></button>)}{locationQuery && !addressResults.length && <div className="modal-error">לא מצאנו כתובת. נסו לכתוב עיר או רחוב אחר.</div>}{locationError && <div className="modal-error">{locationError}</div>}<small className="privacy-hint">🔒 לא נשמור את הכתובת שלכם.</small></section></div>}
    {compareOpen && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setCompareOpen(false); }}><section className="modal compare-modal" role="dialog" aria-modal="true" aria-labelledby="compare-title"><button className="modal-close" onClick={() => setCompareOpen(false)} aria-label="סגירת חלון">×</button><span className="eyebrow">השוואת סל</span><h2 id="compare-title">איפה הסל שלך משתלם יותר?</h2><p>המחירים כוללים מבצעים ציבוריים. הטבות מועדון מוצגות בנפרד.</p><div className="compare-table">{stores.map((store) => { const total = calculateBasket(basket, store.id); const selected = store.id === selectedStore; return <button className={`compare-row ${selected ? 'selected' : ''}`} key={store.id} onClick={() => { chooseStore(store.id); setCompareOpen(false); }}><span className={`store-logo ${store.color}`}>{store.chain.slice(0, 1)}</span><span><strong>{store.name}</strong><small>{formatDistance(store.distanceKm)} · {total.unavailable.length ? `${total.unavailable.length} חסרים` : 'הכל זמין'}</small></span><b>{money(total.publicTotal)}</b>{selected && <em>נבחר</em>}</button>; })}</div><p className="modal-footnote">ההשוואה היא לפי המחירים שנקלטו לאחרונה. המחיר בקופה הוא הקובע.</p></section></div>}
  </main>;
}
